// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh319IYvDNZF5WV0P8XmjeJ6Q1SOH9ntk',
    appId: '1:509022153033:web:0c989cbc4a6e9e2e96d298',
    messagingSenderId: '509022153033',
    projectId: 'mbtigroup-4b280',
    authDomain: 'mbtigroup-4b280.firebaseapp.com',
    storageBucket: 'mbtigroup-4b280.firebasestorage.app',
    measurementId: 'G-43GFS0ZTRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0o_GsUmvT6iny1EMIzVFZsIxParfuwM',
    appId: '1:509022153033:android:0fa1d3c7d33bb07896d298',
    messagingSenderId: '509022153033',
    projectId: 'mbtigroup-4b280',
    storageBucket: 'mbtigroup-4b280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIjXGUKXGjx7dlYcm_qtQ_uf-KB3soBg',
    appId: '1:509022153033:ios:02d95bd6f4d0ae8896d298',
    messagingSenderId: '509022153033',
    projectId: 'mbtigroup-4b280',
    storageBucket: 'mbtigroup-4b280.firebasestorage.app',
    iosBundleId: 'com.example.appBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmIjXGUKXGjx7dlYcm_qtQ_uf-KB3soBg',
    appId: '1:509022153033:ios:02d95bd6f4d0ae8896d298',
    messagingSenderId: '509022153033',
    projectId: 'mbtigroup-4b280',
    storageBucket: 'mbtigroup-4b280.firebasestorage.app',
    iosBundleId: 'com.example.appBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq5z3wktmNG1Y7PlTjTr6zpmlif4hLLsQ',
    appId: '1:509022153033:web:7dbf6871c96304ef96d298',
    messagingSenderId: '509022153033',
    projectId: 'mbtigroup-4b280',
    authDomain: 'mbtigroup-4b280.firebaseapp.com',
    storageBucket: 'mbtigroup-4b280.firebasestorage.app',
    measurementId: 'G-L3H3WFPSVY',
  );

}